#!/usr/bin/env python3
"""Apply reviewed 1.8 semantic matches to a disposable Spectron IDA copy.

The map is generated by ``match_spectron_semantic_functions.py``.  It uses
only function-level evidence and prefixes every imported label with ``v18_``.
The default mode is review-only.  Set ``SPECTRON_TRANSLATION_APPLY=1`` and
provide a new ``SPECTRON_TRANSLATION_SAVE_PATH`` to persist a copy.  Existing
files are never overwritten.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import ida_auto
import ida_bytes
import ida_funcs
import ida_idaapi
import ida_loader
import ida_name


REPO = Path("/home/v/Desktop/graal-decomp/libqplay")
MAP_PATH = Path(
    os.environ.get(
        "SPECTRON_TRANSLATION_MAP",
        str(REPO / "artifacts/spectron_semantic_function_translation_20260826.json"),
    )
)
APPLY = os.environ.get("SPECTRON_TRANSLATION_APPLY") == "1"
INCLUDE_MEDIUM = os.environ.get("SPECTRON_TRANSLATION_INCLUDE_MEDIUM") == "1"
SAVE_PATH = os.environ.get("SPECTRON_TRANSLATION_SAVE_PATH")
REPORT_PATH = Path(
    os.environ.get(
        "SPECTRON_TRANSLATION_REPORT",
        "/tmp/spectron_translation_application_20260826.json",
    )
)


def load_matches() -> list[dict]:
    document = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    if document.get("artifact") != "spectron_semantic_function_translation":
        raise RuntimeError("unexpected Spectron translation artifact")
    matches = document["matches"]
    if INCLUDE_MEDIUM:
        return matches
    return [item for item in matches if item["confidence"] == "high"]


def append_comment(ea: int, match: dict) -> bool:
    comment = (
        "Cross-build semantic match from original 1.8: "
        + match["original_name"]
        + "; method="
        + match["method"]
        + "; size="
        + str(match["size"])
        + "; blocks="
        + str(match["basic_block_count"])
        + "; normalized targets are address-independent"
    )
    existing = ida_bytes.get_cmt(ea, False) or ""
    if comment in existing:
        return False
    ida_bytes.set_cmt(ea, comment if not existing else existing + " | " + comment, False)
    return True


def main() -> None:
    ida_auto.auto_wait()
    matches = load_matches()
    failures = []
    renamed = 0
    comments = 0
    plan = []
    for match in matches:
        ea = int(match["spectron_ea"], 16)
        alias = match["alias_name"]
        function = ida_funcs.get_func(ea)
        item = {
            "spectron_ea": match["spectron_ea"],
            "original_ea": match["original_ea"],
            "original_name": match["original_name"],
            "alias_name": alias,
            "actual_name_before": ida_name.get_name(ea),
            "confidence": match["confidence"],
        }
        if function is None or function.start_ea != ea:
            item["error"] = "address is not the expected Spectron function start"
            failures.append(item)
            plan.append(item)
            continue
        existing_ea = ida_name.get_name_ea(ida_idaapi.BADADDR, alias)
        if existing_ea not in (ida_idaapi.BADADDR, ea):
            item["error"] = "alias is already used at 0x%x" % existing_ea
            failures.append(item)
            plan.append(item)
            continue
        if APPLY:
            if not ida_name.set_name(ea, alias, ida_name.SN_NOCHECK):
                item["error"] = "IDA rejected the alias"
                failures.append(item)
                plan.append(item)
                continue
            renamed += 1
            if append_comment(ea, match):
                comments += 1
        item["actual_name_after"] = ida_name.get_name(ea)
        plan.append(item)

    result = {
        "artifact": "spectron_translation_application",
        "map_path": str(MAP_PATH),
        "apply": APPLY,
        "include_medium": INCLUDE_MEDIUM,
        "save_path": SAVE_PATH,
        "match_count": len(matches),
        "resolved_count": len(matches) - len(failures),
        "renamed_count": renamed,
        "comments_added": comments,
        "failure_count": len(failures),
        "failures": failures,
        "plan": plan,
    }
    if APPLY and SAVE_PATH:
        output = Path(SAVE_PATH).expanduser().resolve()
        if output.exists():
            raise RuntimeError("refusing to overwrite an existing Spectron IDA copy")
        if output.suffix != ".i64":
            raise RuntimeError("SPECTRON_TRANSLATION_SAVE_PATH must end in .i64")
        output.parent.mkdir(parents=True, exist_ok=True)
        if not ida_loader.save_database(str(output), ida_loader.DBFL_COMP):
            raise RuntimeError("IDA could not save the Spectron translation copy")
        result["saved"] = True
    else:
        result["saved"] = False

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({key: result[key] for key in ("apply", "include_medium", "match_count", "resolved_count", "renamed_count", "failure_count", "saved")}, sort_keys=True))


if __name__ == "__main__":
    main()
